services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp-app
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: bit24-blog
      WORDPRESS_DB_USER: bit24
      WORDPRESS_DB_PASSWORD: bit24
    depends_on:
      - db
    networks:
      - wpnet

  db:
    image: mysql:8.0
    container_name: wp-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bit24-blog
      MYSQL_USER: bit24
      MYSQL_PASSWORD: bit24
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  nginx:
    image: nginx:latest
    container_name: wp-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - wordpress
    networks:
      - wpnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    volumes:
      - ./phpmyadmin/conf.d:/usr/local/etc/php/conf.d
    depends_on:
      - db
    networks:
      - wpnet

volumes:
  db_data:

networks:
  wpnet:
    driver: bridge
